--DROP DATABASE EXM_MAFIA
CREATE DATABASE EXM_MAFIA

GO 
USE EXM_MAFIA
GO

--TABLAS SIMPLES, Y RELACIONES 1:1 O/Y 1:N

--TABLA DE LOS PADRINOS
CREATE TABLE PADRINOS
(
ID INT IDENTITY (1,1) CONSTRAINT PK_PADRINOS PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
FECHA_NACIMIENTO DATE ,
PROCEDENCIA VARCHAR(20),
)

--TABLA DE LOS CONSIGLIERES (RELACIONADO CON TABLA PADRINOS)
CREATE TABLE CONSIGLIERES
(
NOMBRE VARCHAR(20) NOT NULL,
APELLIDOS VARCHAR(50) NOT NULL,
ID_PADRINO INT,
APODO VARCHAR(20),
FECHA_NACIMIENTO DATE NOT NULL,
PROCEDENCIA VARCHAR (20)NOT NULL,
TITULACION VARCHAR(50),

CONSTRAINT FK_PADRINO_CONSIGLIERE FOREIGN KEY(ID_PADRINO) REFERENCES PADRINOS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE NEGOCIOS
CREATE TABLE NEGOCIOS
(
ID SMALLINT CONSTRAINT PK_NEGOCIOS PRIMARY KEY,
DENOMINACION VARCHAR(100) ,
LEGAL CHAR(1)NOT NULL,
)

--TABLA DE TERRITORIOS
CREATE TABLE TERRITORIOS
(
ID INT CONSTRAINT PK_TERIITORIOS PRIMARY KEY,
CIUDAD VARCHAR(20) NOT NULL,
BARRIO VARCHAR(30) NOT NULL,
)


--TABLA DE LAS FAMILIAS
CREATE TABLE FAMIGLIAS
(
NOMBRE VARCHAR(50) CONSTRAINT PK_FAMIGLIAS PRIMARY KEY,
PROCEDENCIA VARCHAR(20),
)

--TABLA DE LOS CAPOS(RELACIONADO CON TABLA FAMIGLIAS)
CREATE TABLE CAPOS
(
ID INT CONSTRAINT OK_CAPOS PRIMARY KEY,
NOMBRE VARCHAR(20)NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL,
APODO VARCHAR(20),
FECHA_NACIMIENTO DATE,
NOMBRE_FAMIGLIA VARCHAR(50),
PROCEDENCIA VARCHAR(30),

CONSTRAINT FK_CAPO_FAMIGLIA FOREIGN KEY (NOMBRE_FAMIGLIA) REFERENCES FAMIGLIAS (NOMBRE)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE LUGARTENIENTES (RELACIONADO CON LA TABLA CAPOS)
CREATE TABLE LUGARTENIENTES
(
ID INT CONSTRAINT PK_LUGARTENIENTE PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDOS VARCHAR(30) NOT NULL,
APODO VARCHAR (20),
ID_CAPO INT,

CONSTRAINT FK_LUGARTENIENTE_CAPO FOREIGN KEY (ID_CAPO) REFERENCES CAPOS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE SOLDADOS (RELACIONADO CON LA TABLA CAPOS)
CREATE TABLE SOLDATOS 
(
ID INT CONSTRAINT PK_SOLDATOS PRIMARY KEY,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDOS VARCHAR(30)NOT NULL,
APODO VARCHAR (20),
FECHA_NACIMIENTO DATE,
PROCEDENCIA VARCHAR(20),
TATUAJE_PRINCIPAL VARCHAR(20),
ID_CAPO INT,

CONSTRAINT FK_SOLDATO_CAPO FOREIGN KEY (ID_CAPO) REFERENCES CAPOS (ID)
ON UPDATE CASCADE ON DELETE NO ACTION,
)


--TABLA TECNICAS DE PERSUACION
CREATE TABLE [TECNICAS DE PERSUACION]
(
ID SMALLINT CONSTRAINT PK_TECNICAS PRIMARY KEY,
DENOMINACION VARCHAR(50)NOT NULL,
)


--TABLA DE ARMAS
CREATE TABLE ARMAS
(
ID INT CONSTRAINT PK_ARMAS PRIMARY KEY,
DENOMINACION VARCHAR (30),
ILEGAL CHAR(1),
LICENCIA CHAR(1),
)

--TABLAS DE GENERALIZACIONES 

--TABLA DE ARMAS BLANCAS
CREATE TABLE [ARMAS BLANCAS]
(
ID INT CONSTRAINT PK_ARMAS_BLANCAS PRIMARY KEY,
[LONGITUD DE HOJA] SMALLINT NOT NULL,
[TIPO FILO] CHAR(10) NOT NULL,
RETRACTIL CHAR(1),

CONSTRAINT FK_ARMAS_BLANCAS FOREIGN KEY (ID) REFERENCES ARMAS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE ARMAS DE FUEGO
CREATE TABLE [ARMAS DE FUEGO]
(
ID INT CONSTRAINT PK_ARMAS_FUEGO PRIMARY KEY,
MARCA VARCHAR(10)NOT NULL,
MODELO VARCHAR(10)NOT NULL,
CALIBRE TINYINT NOT NULL,
[CAPACIDAD DE PROYECTILES] TINYINT NOT NULL,

CONSTRAINT FK_ARMAS_FUEGO FOREIGN KEY (ID) REFERENCES ARMAS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE CAPOREGIME
CREATE TABLE CAPOREGIME
(
ID INT CONSTRAINT PK_CAPOREGIME PRIMARY KEY,
[PORCENTAJE DE COMISION] TINYINT NOT NULL,

CONSTRAINT FK_CAPOREGIME FOREIGN KEY (ID) REFERENCES CAPOS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE CAPODECIME
CREATE TABLE CAPODECIME
(
ID INT CONSTRAINT PK_CAPODECIME PRIMARY KEY,
SUELDO INT,
[FECHA DE CONTRATACION] DATE,

CONSTRAINT FK_CAPODECIME FOREIGN KEY (ID) REFERENCES CAPOS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
)

--TABLA DE RELACIONES

--TABLA DE PROTECCION DE LAS FAMILIAS
CREATE TABLE PROTECCION_FAMILIAS
(
FAMIGLIA_PROTECTORA VARCHAR(50),
FAMIGLIA_PROTEGIDA VARCHAR(50),

CONSTRAINT FK_FAMIGLIA_PROTEGIDA FOREIGN KEY (FAMIGLIA_PROTEGIDA) REFERENCES FAMIGLIAS (NOMBRE)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_FAMIGLIA_PROTECTORA FOREIGN KEY (FAMIGLIA_PROTECTORA) REFERENCES FAMIGLIAS (NOMBRE)
ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT PK_FAMIGLIA_PROTECCION PRIMARY KEY (FAMIGLIA_PROTECTORA, FAMIGLIA_PROTEGIDA),
)

--TABLA DE PADRINOS_FAMIGLIA (HACEMOS ESTA TABLA PARA INCLUIR EL ATRIBUTO DE LA RELACION DEL PADRINO CON LA FAMIGLIA)
CREATE TABLE PADRINO_FAMIGLIAS
(
ID_PADRINO INT,
NOMBRE_FAMIGLIA VARCHAR(50),
[FECHA DE NOMBRAMIENTO] DATE NOT NULL,

CONSTRAINT FK_PADRINO_FAMIGLIA FOREIGN KEY (ID_PADRINO) REFERENCES PADRINOS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_FAMIGLIA_PADRINO FOREIGN KEY (NOMBRE_FAMIGLIA) REFERENCES FAMIGLIAS (NOMBRE)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT PK_PADRINO_FAMIGLIAS PRIMARY KEY (ID_PADRINO, NOMBRE_FAMIGLIA),
)

--TABLA DE FAMIGLIA_NEGOCIO_TERRITORIO
CREATE TABLE FAMIGLIA_NEGOCIO_TERRITORIO
(
ID_TERRITORIO INT,
ID_NEGOCIO SMALLINT,
NOMBRE_FAMIGLIA VARCHAR(50),

CONSTRAINT FK_TERRITORIO FOREIGN KEY (ID_TERRITORIO) REFERENCES TERRITORIOS (ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT FK_NEGOCIOS FOREIGN KEY (ID_NEGOCIO) REFERENCES NEGOCIOS (ID)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_FAMIGLIA_NEGOCIO FOREIGN KEY (NOMBRE_FAMIGLIA) REFERENCES FAMIGLIAS (NOMBRE)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT PK_FAMIGLIA_NEGOCIO_TERRITORIO PRIMARY KEY (ID_TERRITORIO, ID_NEGOCIO),
)

--TABLA DE TECNICA USADA POR CAPOS
CREATE TABLE CAPOS_TECNICAS
(
ID_CAPO INT,
ID_TECNICA SMALLINT,

CONSTRAINT FK_CAPO_TECNICA FOREIGN KEY (ID_CAPO) REFERENCES CAPOS (ID)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_TECNICA_CAPO FOREIGN KEY (ID_TECNICA) REFERENCES [TECNICAS DE PERSUACION] (ID)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT PK_CAPOS_TECNICAS PRIMARY KEY (ID_CAPO,ID_TECNICA),
)

--POR FIN ULTIMA TABLA RELACIONA A LOS SOLDATOS CON LAS ARMAS
CREATE TABLE SOLDATOS_ARMAS
(
ID_SOLDATO INT,
ID_ARMAS INT,

CONSTRAINT FK_SOLDATO_ARMAS FOREIGN KEY (ID_SOLDATO) REFERENCES SOLDATOS(ID)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_ARMAS_CAPOS FOREIGN KEY (ID_ARMAS) REFERENCES ARMAS(ID)
ON UPDATE CASCADE ON DELETE CASCADE,
CONSTRAINT PK_SOLDATOS_ARMAS PRIMARY KEY (ID_SOLDATO,ID_ARMAS),
)
