--EJERCICIO 3
GO
USE EXM_MAFIA
GO
--EDADE DE SOLDATOS ENTRE 15 Y 50
ALTER TABLE SOLDATOS ADD CONSTRAINT CK_EDAD_SOLDATO CHECK(((YEAR(CURRENT_TIMESTAMP-CAST(FECHA_NACIMIENTO AS SMALLDATETIME))-1900)>15)AND ((YEAR(CURRENT_TIMESTAMP-CAST(FECHA_NACIMIENTO AS SMALLDATETIME))-1900)<55))

--ARMA ILEGAL DEBE TENER VALOR LICENCIA NULL --ESTAAA ESTA COMPLICADA EN LEO
ALTER TABLE ARMAS ADD CONSTRAINT CK_LICENCIAS CHECK ((ILEGAL='S' AND LICENCIA IS NULL) OR (ILEGAL='N' AND (LICENCIA='N' OR LICENCIA='S')))

--NO PUEDE HABER VARIOS CAPOS CON EL MISMO NICK
ALTER TABLE CAPOS ADD CONSTRAINT UN_NICKS UNIQUE (APODO)

--TIPO DE FILO POEDE SER RECTO CONVEXO SCANDI SERRADO O MIXTO
ALTER TABLE [ARMAS BLANCAS] ADD CONSTRAINT CK_TIPOS_FILOS CHECK ([TIPO FILO] IN ('MIXTO', 'SERRADO','RECTO','CONVEXO','SCANDI'))

--AÑADE COLUMNA CALCULADA A ARMAS FUEGO
ALTER TABLE [ARMAS DE FUEGO] ADD PUPA AS CALIBRE/10*[CAPACIDAD DE PROYECTILES]

--COLUMNA PROCEDENCIA DE CAPOS VALOR POR DEFECTO SILICIA
ALTER TABLE CAPOS ADD CONSTRAINT DF_PROCEDENCIA DEFAULT 'SILICIA' FOR PROCEDENCIA

GO
USE EXM_MAFIA
GO

-- EJERCICIO 4 CREA TABLA DELITOS Y AÑADELE RESTRICCION
--ALTER TABLE DELITOS DROP COLUMN ID
--ALTER TABLE DELITOS ADD ID INT CONSTRAINT PK_DELITOS PRIMARY KEY
CREATE TABLE DELITOS
(
ID INT CONSTRAINT PK_DELITOS PRIMARY KEY,
DENOMINACION VARCHAR(20),
ARTICULO_CP DECIMAL(3,1),
CONDENA_MIN TINYINT,
CONDENA_MAX TINYINT,

CONSTRAINT CK_CONDENAS CHECK (CONDENA_MAX>=CONDENA_MIN AND CONDENA_MAX<=360)
)

--EJERCICIO 5
CREATE TABLE DELITOS_CAPOS
(
ID_DELITO INT,
ID_CAPO INT,
FECHA_COMETIO DATE,

CONSTRAINT FK_DELITO_CAPO FOREIGN KEY (ID_DELITO) REFERENCES DELITOS (ID)
ON UPDATE CASCADE ON DELETE NO ACTION,
CONSTRAINT FK_CAPO_DELITO FOREIGN KEY (ID_CAPO) REFERENCES CAPOS (ID)
ON UPDATE CASCADE ON DELETE NO ACTION,

CONSTRAINT PK_DELITOS_CAPOS PRIMARY KEY (ID_CAPO,FECHA_COMETIO)
)

CREATE TABLE DELITOS_SOLDATOS
(
ID_DELITO INT,
ID_SOLDATO INT,
FECHA_COMETIO DATE,

CONSTRAINT FK_DELITO_SOLDATO FOREIGN KEY (ID_DELITO) REFERENCES DELITOS (ID),
CONSTRAINT FK_SOLDATO_DELITO FOREIGN KEY (ID_SOLDATO) REFERENCES SOLDATOS (ID),

CONSTRAINT PK_DELITOS_SOLDATOS PRIMARY KEY (ID_SOLDATO,FECHA_COMETIO)
)